### PR TITLE
Update cacert.pem

### PR DESCRIPTION
**Pull request by n10v**

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this! I verified it manually, this matches what `mkcert.org` is producing today.

**Comment by n10v** [comment]
@Lukasa :+1:

**Comment by n10v** [comment]
Also, it will be cool, if you update the gem

**Comment by n10v** [comment]
I'll be very thankful ^^

**Comment by Lukasa** [comment]
I'd like to update the gem, but currently I'm blocked on #3.

**Comment by n10v** [comment]
:(

**Pull request merged**
